# Generated by Django 2.1.5 on 2019-02-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('weight', models.IntegerField()),
                ('prescriptions', models.CharField(max_length=500)),
                ('report', models.FileField(upload_to='')),
            ],
        ),
    ]
